-- Active: 1686116508594@@127.0.0.1@3306
insert INTO restaurants (restaurant_name) VALUES ("Бургер и запятая");

INSERT INTO food_categories (category_name) VALUES ("Популярное");
INSERT INTO food_categories (category_name) VALUES ("Бургеры и Роллы");
INSERT INTO food_categories (category_name) VALUES ("Картофель, стартеры и салаты");
INSERT INTO food_categories (category_name) VALUES ("Кафе");
INSERT INTO food_categories (category_name) VALUES ("Напитки");
INSERT INTO food_categories (category_name) VALUES ("Завтрак");
INSERT INTO food_categories (category_name) VALUES ("Десерты");
INSERT INTO food_categories (category_name) VALUES ("Соусы");

INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 524, 165, "Биг Хит", 1);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 570, 199, "Гранд Де Люкс", 1);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 800, 275, "Биг Спешиал", 1);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 441, 145, "Двойной Чизбургер", 1);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 525, 165, "Чикен Премьер", 1);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "4 шт", 179, 59, "Наггетсы", 1);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "6 шт", 268, 69, "Наггетсы", 1);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "9 шт", 402, 99, "Наггетсы", 1);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "18 шт", 804, 197, "Наггетсы", 1);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 249, 65, "Пирожок Вишневый", 1);

INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 568, 239, "Барселона Бургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 554, 215, "Барселона Бургер с курицей", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 795, 325, "Биг Спешиал Ростбиф", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 524, 165, "Биг Хит", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 711, 225, "Двойной Биг Хит", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 514, 175, "Гранд", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 570, 199, "Гранд Де Люкс", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 732, 259, "Двойной Гранд", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 1098, 361, "Двойной Биг Спешиал", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 800, 275, "Биг Спешиал", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 573, 235, "Биг Спешиал Джуниор", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 441, 145, "Двойной Чизбургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 299, 69, "Чизбургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 251, 57, "Гамбургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 525, 165, "Чикен Премьер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 484, 109, "Чикен Хит", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 337, 59, "Чикен Бургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 331, 171, "Фиш Бургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 475, 235, "Двойной Фиш Бургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 472, 179, "Цезарь Ролл", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 412, 239, "Шримп Ролл", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 525, 199, "Биг Спешиал Ролл", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 1136, 429, "Пара Барселона Бургер", 2);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 1108, 389, "Пара Барселона Бургер с курицей", 2);

INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 232, 109, "Сырные треугольники Чоризо", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 1537, 445, "Большой Снэк Бокс со стрипсами", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 1733, 469, "Большой Снэк Бокс с крыльями", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 284, 65, "Гранд Фри", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 383, 89, "Гранд Фри", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 482, 105, "Гранд Фри", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средние", 499, 103, "Картофельные Дольки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большие", 664, 131, "Картофельные Дольки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 535, 169, "Снэк Бокс", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 866, 239, "Снэк Бокс с крыльями", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "3 шт", 417, 145, "Куриные Крылышки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "5 шт", 695, 215, "Куриные Крылышки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "7 шт", 973, 289, "Куриные Крылышки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "4 шт", 179, 59, "Наггетсы", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "6 шт", 268, 69, "Наггетсы", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "9 шт", 402, 99, "Наггетсы", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "18 шт", 804, 197, "Наггетсы", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "3 шт", 270, 115, "Стрипсы", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "5 шт", 450, 189, "Стрипсы", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "7 шт", 630, 249, "Стрипсы", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "4 шт", 180, 189, "Большие Креветки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "6 шт", 271, 259, "Большие Креветки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "9 шт", 406, 365, "Большие Креветки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 231, 179, "Салат цезарь", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 186, 249, "Салат Цезарь с креветками", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 31, 109, "Овощной салат", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 28, 71, "Морковные палочки", 3);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 38, 71, "Яблочные дольки", 3);

INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 334, 119, "Розан с ванильным кремом", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 567, 185, "Морковный торт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 432, 175, "Лимонный тарт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 197, 79, "Творожник", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 449, 175, "Торт Шоколадный", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 291, 175, "Клубничный Чизкейк", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 260, 165, "Тирамису", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 347, 175, "Торт Миндальный", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 425, 175, "Чизкейк Классический", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 335, 175, "Торт Рикотта с грушей", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 84, 75, "Макарони", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 368, 79, "Печенье Клюква-кокос", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 324, 79, "Печенье Шоколадное с кусочками шоколада", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 371, 185, "Чиабатта с тунцом", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 432, 175, "Чиабатта с ветчиной и сыром", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 306, 139, "Круассан с ветчиной и сыром", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 169, 99, "Круассан", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 155, 149, "Айс Кофе Карамель", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 106, 209, "Айс Кофе Карамель Миндальный", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 114, 209, "Айс Кофе Карамель Кокосовый", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 326, 189, "Апельсиновый Раф", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 31, 129, "Миндальный Капучино", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 44, 169, "Миндальный Капучино", 4);;
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 57, 189, "Миндальный Капучино", 4);;
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 42, 129, "Кокосовый Капучино", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 59, 169, "Кокосовый Капучино", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 76, 189, "Кокосовый Капучино", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 70, 69, "Капучино", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 110, 109, "Капучино", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 130, 129, "Капучино", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 50, 169, "Миндальный Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 54, 189, "Миндальный Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 67, 169, "Кокосовый Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 72, 189, "Кокосовый Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 120, 109, "Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 130, 129, "Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 44, 215, "Миндальный Флэт Уайт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 63, 270, "Миндальный Флэт Уайт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 59, 215, "Кокосовый Флэт Уайт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 84, 270, "Кокосовый Флэт Уайт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 113, 155, "Флэт Уайт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 156, 210, "Флэт Уайт", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 135, 215, "Миндальный Пряный Чай Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 156, 215, "Кокосовый Пряный Чай Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 229, 155, "Пряный Чай Латте", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 7, 59, "Американо", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 10, 85, "Американо", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 14, 99, "Американо", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 174, 155, "Венский кофе", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 177, 210, "Венский кофе", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 319, 185, "Горячий Шоколад", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 285, 155, "Раф", 4);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 316, 210, "Раф", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 40, 99, "Чай черный Эрл Грей", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 40, 99, "Чай Черный с чабрецом", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 40, 99, "Чай Хуго Коктейль", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 2, 69, "Двойной Эспрессо", 4);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 50, 99, "Артезианская вода Белоголовка негазированная 0,4 л. - артезианская вода без газа", 4);

INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 245, 119, "Молочный коктейль Тропик", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 80, 109, "Лимонад Спелая слива - красная смородина", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 176, 129, "Санрайз Спелая слива - красная смородина", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, 155, 149, "Айс Кофе Карамель", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 1, 89, "Добрый Кола без сахара", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 2, 99, "Добрый Кола без сахара", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 3, 109, "Добрый Кола без сахара", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 106, 89, "Добрый Кола", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 170, 99, "Добрый Кола", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 212, 109, "Добрый Кола", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 80, 89, "Добрый Апельсин", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 128, 99, "Добрый Апельсин", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 160, 109, "Добрый Апельсин", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", 46, 89, "Добрый Лимон-Лайм", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 74, 99, "Добрый Лимон-Лайм", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 92, 109, "Добрый Лимон-Лайм", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленьки", 247, 89, "Молочный Коктейль Шоколадный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", 386, 119, "Молочный Коктейль Шоколадный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", 493, 155, "Молочный Коктейль Шоколадный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", "Молочный Коктейль Клубничный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", "Молочный Коктейль Клубничный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", "Молочный Коктейль Клубничный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Маленький", "Молочный Коктейль Ванильный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Средний", "Молочный Коктейль Ванильный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_size, position_calories, position_price, position_name, food_category_id) VALUES (1, "Большой", "Молочный Коктейль Ванильный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Артезианская вода Белоголовка негазированная 0,4 л. - артезианская вода без газа", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Липтон Зеленый", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Липтон Лимон", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Апельсиновый сок", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Яблочный сок", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Капучино", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Латте", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Чай Черный Эрл Грей", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Чай Черный", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Чай Зеленый", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Американо", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кофе Глясе", 5);
INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Двойной Эспрессо", 5);

-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Физз Карамель", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Черничное", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Молочный коктейль Тропик", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Лимонад Спелая слива - красная смородина", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Санрайз Спелая слива - красная смородина", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Манго-маракуйя", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Кофе Карамель", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Добрый Кола без сахара", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Добрый Кола", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Добрый Апельсин", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Добрый Лимон-Лайм", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Молочный Коктейль Шоколадный", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Молочный Коктейль Клубничный", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Молочный Коктейль Ванильный", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Артезианская вода Белоголовка негазированная 0,4 л. - артезианская вода без газа", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Липтон Зеленый", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Липтон Лимон", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Апельсиновый сок", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Яблочный сок", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Капучино", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Латте", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Чай Черный Эрл Грей", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Чай Черный", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Чай Зеленый", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Американо", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кофе Глясе", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Двойной Эспрессо", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Шоколадное", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Шоколадно-клубничное", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Шоколадно-карамельное", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Карамельное", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Шоколадное", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Клубничное", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Вафельный рожок", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Пирожок Клубника-персик", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Пирожок Вишневый", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Яблочное Пюре", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Сырный соус + Кисло-Сладкий соус", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Сырный соус + Сырный соус", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кисло-Сладкий соус + Кисло-Сладкий соус", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Сырный соус", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кисло-Сладкий соус", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Терияки", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус 1000 островов", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Чесночный", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Горчичный", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кетчуп", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Сладкий чили", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Барбекю", 6);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Оливковое масло", 6);

-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Черничное", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Манго-маракуйя", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Шоколадное", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Шоколадно-клубничное", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Айс Де Люкс Шоколадно-карамельное", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Карамельное", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Шоколадное", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Мороженое Клубничное", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Вафельный рожок", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Пирожок Клубника-персик", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Пирожок Вишневый", 7);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Яблочное Пюре", 7);

-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Сырный соус + Кисло-Сладкий соусцыфы", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Сырный соус + Сырный соус", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кисло-Сладкий соус + Кисло-Сладкий соус", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Сырный соус", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кисло-Сладкий соус", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Терияки", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус 1000 островов", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Чесночный", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Горчичный", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Кетчуп", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Сладкий чили", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Барбекю", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Соус Цезарь", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Оливковое масло", 8);
-- INSERT INTO restaurant_menu (restaurant_id, position_calories, position_price, position_name, food_category_id) VALUES (1, "Влажная салфетка", 8);

-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (1, "Обычный", 165);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (1, "Обычный", 199);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (2, "Обычный", 275);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (3, "Обычный", 145);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (4, "Обычный", 165);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (5, "3 шт", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (5, "5 шт", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (5, "8 шт", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (5, "18 шт", 195);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (6, "Обычный", 65);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (7, "Обычный", 239);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (8, "Обычный", 215);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (10, "Обычный", 325);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (11, "Обычный", 165);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (12, "Обычный", 225);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (13, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (14, "Обычный", 199);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (15, "Обычный", 259);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (16, "Обычный", 361);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (17, "Обычный", 275);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (18, "Обычный", 235);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (19, "Обычный", 145);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (20, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (21, "Обычный", 57);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (22, "Обычный", 165);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (23, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (24, "Обычный", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (25, "Обычный", 195);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (26, "Обычный", 235);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (27, "Обычный", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (28, "Обычный", 229);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (29, "Обычный", 209);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (30, "Обычный", 429);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (31, "Обычный", 389);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (32, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (33, "Обычный", 445);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (34, "Обычный", 469);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (35, "Маленький", 65);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (35, "Средний", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (35, "Большой", 105);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (36, "Средние", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (36, "Большие", 125);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (37, "Обычный", 169);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (38, "Обычный", 249);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (39, "2 шт", 145);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (39, "4 шт", 215);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (39, "6 шт", 289);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (40, "3 шт", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (40, "5 шт", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (40, "8 шт", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (40, "18 шт", 195);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (41, "2 шт", 115);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (41, "4 шт", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (41, "6 шт", 249);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (42, "3 шт", 219);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (42, "5 шт", 285);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (42, "8 шт", 379);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (43, "Обычный", 179);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (44, "Обычный", 239);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (45, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (46, "Обычный", 71);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (47, "Обычный", 71);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (48, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (49, "Обычный", 185);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (50, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (51, "Обычный", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (52, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (53, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (54, "Обычный", 165);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (55, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (56, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (57, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (58, "1 шт", 75);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (59, "Обычный", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (60, "Обычный", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (61, "Обычный", 185);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (62, "Обычный", 175);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (63, "Обычный", 139);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (64, "Обычный", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (65, "Обычный", 149);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (66, "Обычный", 209);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (67, "Обычный", 209);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (68, "Обычный", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (69, "Средний", 169);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (69, "Большой", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (70, "Маленький", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (70, "Средний", 169);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (70, "Большой", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (71, "Маленький", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (71, "Средний", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (71, "Большой", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (72, "Средний", 169);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (72, "Большой", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (73, "Средний", 169);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (73, "Большой", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (74, "Средний", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (74, "Большой", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (75, "Средний", 209);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (75, "Большой", 249);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (76, "Средний", 209);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (76, "Большой", 249);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (77, "Средний", 149);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (77, "Большой", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (78, "Обычный", 209);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (79, "Обычный", 209);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (80, "Обычный", 149);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (81, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (81, "Средний", 85);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (81, "Большой", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (82, "Средний", 149);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (82, "Большой", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (83, "Обычный", 179);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (84, "Средний", 149);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (84, "Большой", 189);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (85, "Обычный", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (86, "Обычный", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (87, "Обычный", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (88, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (89, "Обычный", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (90, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (91, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (92, "Обычный", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (93, "Обычный", 149);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (94, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (94, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (94, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (95, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (95, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (95, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (96, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (96, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (96, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (97, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (97, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (97, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (98, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (98, "Средний", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (98, "Большой", 155);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (99, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (99, "Средний", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (99, "Большой", 155);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (100, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (100, "Средний", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (100, "Большой", 155);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (101, "Обычный", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (102, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (102, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (102, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (103, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (103, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (103, "БОльшой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (104, "Маленький", 92);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (104, "Средний", 105);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (104, "Большой", 115);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (105, "Маленький", 92);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (105, "Средний", 105);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (105, "Большой", 115);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (106, "Маленький", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (106, "Средний", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (106, "Большой", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (107, "Средний", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (107, "Большой", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (108, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (108, "Средний", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (109, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (109, "Средний", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (110, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (110, "Средний", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (111, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (111, "Средний", 85);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (111, "Большой", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (112, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (113, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (114, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (115, "Обычный", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (116, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (117, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (118, "Обычный", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (119, "Обычный", 125);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (120, "Обычный", 149);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (121, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (121, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (121, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (122, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (122, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (122, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (123, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (123, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (123, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (124, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (124, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (124, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (125, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (125, "Средний", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (125, "Большой", 155);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (126, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (126, "Средний", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (126, "Большой", 155);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (127, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (127, "Средний", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (127, "Большой", 155);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (128, "Обычный", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (129, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (129, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (129, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (130, "Маленький", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (130, "Средний", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (130, "Большой", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (131, "Маленький", 92);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (131, "Средний", 105);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (131, "Большой", 115);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (132, "Маленький", 92);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (132, "Средний", 105);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (132, "Большой", 115);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (133, "Маленький", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (133, "Средний", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (133, "Большой", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (134, "Средний", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (134, "Большой", 129);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (135, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (135, "Средний", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (136, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (136, "Средний", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (137, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (137, "Средний", 79);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (138, "Маленький", 59);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (138, "Средний", 85);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (138, "Большой", 99);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (139, "Обычный", 109);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (140, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (141, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (142, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (143, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (144, "Обычный", 84);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (145, "Обычный", 84);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (146, "Обычный", 84);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (147, "Обычный", 39);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (148, "Обычный", 74);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (149, "Обычный", 65);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (150, "Обычный", 71);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (151, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (152, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (153, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (154, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (155, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (156, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (157, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (158, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (159, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (160, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (161, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (162, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (163, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (164, "Обычный", 89);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (165, "Обычный", 125);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (166, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (167, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (168, "Обычный", 119);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (169, "Обычный", 84);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (170, "Обычный", 84);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (171, "Обычный", 84);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (172, "Обычный", 39);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (173, "Обычный", 74);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (174, "Обычный", 65);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (175, "Обычный", 71);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (176, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (177, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (178, "Обычный", 69);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (179, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (180, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (181, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (182, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (183, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (184, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (185, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (186, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (187, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (188, "Обычный", 40);
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (189, "Обычный", 40);  
-- INSERT INTO product_sizes (product_id, size_name, price) VALUES (190, "Обычный", 4);

-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 1, "524");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 1, "570");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 2, "340");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 3, "441");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 4, "525");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 5, "268");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 6, "249");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 7, "568");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 8, "554");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 10, "795");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 11, "529");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 12, "711");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 13, "514");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 14, "570");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 15, "732");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 16, "1098");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 17, "800");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 18, "573");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 19, "441");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 20, "299");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 21, "251");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 22, "525");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 23, "484");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 24, "337");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 25, "331");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 26, "475");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 27, "472");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 28, "412");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 29, "525");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 30, "1136");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 31, "1108");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 32, "232");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 33, "1537");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 34, "1733");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 35, "284");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 36, "499");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 37, "599");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 38, "930");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 39, "417");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 40, "179");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 41, "270");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 42, "180");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 43, "231");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 44, "186");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 45, "31");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 46, "28");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 47, "38");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 48, "334");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 49, "567");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 50, "432");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 51, "197");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 52, "449");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 53, "291");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 54, "260");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 55, "347");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 56, "425");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 57, "335");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 58, "84");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 59, "368");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 60, "324");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 61, "371");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 62, "432");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 63, "306");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 64, "169");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 65, "155");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 66, "106");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 67, "114");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 68, "326");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 69, "44");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 70, "42");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 71, "70");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 72, "50");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 73, "67");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 74, "120");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 75, "44");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 76, "59");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 77, "113");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 78, "135");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 79, "156");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 80, "229");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 81, "6");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 82, "174");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 83, "319");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 84, "285");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 85, "20");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 86, "20");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 87, "20");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 88, "1");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 89, "10");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 90, "245");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 91, "80");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 92, "176");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 93, "155");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 94, "0.7");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 95, "170");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 96, "80");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 97, "46");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 98, "247");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 99, "244");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 100, "244");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 101, "10");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 102, "67");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 103, "67");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 104, "150");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 105, "101");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 106, "70");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 107, "120");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 108, "20");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 109, "20");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 110, "20");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 111, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 112, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 113, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 114, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 115, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 116, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 117, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 118, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 119, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 120, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 121, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 122, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 123, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 124, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 125, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 126, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 127, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 128, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 129, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 130, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 131, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 132, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 133, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 134, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 135, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 136, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 137, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 138, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 139, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 140, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 141, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 142, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 143, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 144, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 145, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 146, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 147, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 148, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 149, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 150, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 151, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 152, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 153, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 154, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 155, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 156, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 157, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 158, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 159, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 160, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 161, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 162, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 163, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 164, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 165, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 166, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 167, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 168, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 169, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 170, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 171, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 172, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 173, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 174, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 175, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 176, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 177, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 178, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 179, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 180, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 181, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 182, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 183, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 184, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 185, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 186, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 187, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 188, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 189, "");
-- INSERT INTO product_attributes (attribute_name, product_id, attribute_value) VALUES (1, "Сытость", 190, "");


INSERT INTO levels (level_number, level_entry_score) VALUES (18, 0);
INSERT INTO levels (level_number, level_entry_score) VALUES (19, 100);
INSERT INTO levels (level_number, level_entry_score) VALUES (20, 200);
INSERT INTO levels (level_number, level_entry_score) VALUES (21, 300);
INSERT INTO levels (level_number, level_entry_score) VALUES (22, 400);
INSERT INTO levels (level_number, level_entry_score) VALUES (23, 500);
INSERT INTO levels (level_number, level_entry_score) VALUES (24, 600);
INSERT INTO levels (level_number, level_entry_score) VALUES (25, 700);
INSERT INTO levels (level_number, level_entry_score) VALUES (26, 850);
INSERT INTO levels (level_number, level_entry_score) VALUES (27, 1000);

INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Безработный", "Безработный", 0);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Дворник", "Мети дворы", 10);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Лесоруб", "Руби деревья", 25);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Шахтер", "Копай руду", 35);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Дальнобойщик", "Достовляй", 100);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Каменотес", "Обрабатывай камень", 50);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Лесопилка", "Обрабатывай дерево", 60);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Плавильня", "Плавь металл", 55);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Металлозавод", "Обрабытывай металл", 75);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Стройка", "Строй здания", 100);
INSERT INTO jobs (job_name, job_description, job_salary) VALUES ("Завод автозапчастей", "Делай автозапчасти", 150);

INSERT INTO jobs_levels (level_id, job_id) VALUES (1, 2);
INSERT INTO jobs_levels (level_id, job_id) VALUES (2, 3);
INSERT INTO jobs_levels (level_id, job_id) VALUES (3, 4);
INSERT INTO jobs_levels (level_id, job_id) VALUES (4, 5);
INSERT INTO jobs_levels (level_id, job_id) VALUES (5, 6);
INSERT INTO jobs_levels (level_id, job_id) VALUES (6, 7);
INSERT INTO jobs_levels (level_id, job_id) VALUES (7, 8);
INSERT INTO jobs_levels (level_id, job_id) VALUES (8, 9);
INSERT INTO jobs_levels (level_id, job_id) VALUES (9, 10);
INSERT INTO jobs_levels (level_id, job_id) VALUES (10, 11);
